---
# example requirements.yml
roles:
  # Install a role from Ansible Galaxy.
  - name: geerlingguy.apache
    src: geerlingguy.apache
    version: 4.0.0

collections:
  # Install a collection from Ansible Galaxy.
  - name: community.general
    version: ">=7.0.0"
    source: https://galaxy.ansible.com
